### ISSUE TITLE
Add support for CloudFront ResponseHeadersPolicy

### ISSUE THREAD

**Issue by joris974** [mbj/stratosphere#194]
CloudFront supports attaching a ResponseHeadersPolicy to CloudFront Distribution: https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_ResponseHeadersPolicy.html 

This feature also exists in CloudFormation : https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudfront-responseheaderspolicy.html 

Is it possible to add support for creating and attaching ResponseHeadersPolicy in Stratosphere?
Thank you!

**Comment by mbj** [comment]
@joris974 Its likely that this fields are in the current cloudformation specification and this library "just" has to be regenerated to make this feature available.

Since I took over maintainer-ship I was focusing on aeson-2 support.  And have yet to start regenerating this library. I'd be happy you beat me to it via a PR.

**Comment by joris974** [comment]
I am not sure how to regenerate the library.
The Readme is mentioning a `build` script but it doesn't exist in the repo anymore.

**Comment by mbj** [comment]
@joris974 I'm working on a bigger refactoring that will make stratosphere generate one library per AWS service, and during this process also regenerate the library.

The current generator is not "out of the box" compatible with newer resource specs anymore, so needs updates anyway. So sorry this will take a while but from there updates should be much easier.

**Comment by mbj** [comment]
This was addressed via #207 (unreleased) and a major breaking API change I've yet to better document.
